version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wb_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: wb_analytics
      DB_USER: postgres
      DB_PASSWORD: postgres
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:postgres@db:5432/wb_analytics"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app

volumes:
  postgres_data: